name: Set up project
description: Set up ruby, javascript, dependencies, and database
inputs:
  rails_env:
    description: RAILS_ENV to set. Defaults to test
    required: false
    default: test
  database_url:
    description: DATABASE_URL to set
    required: false
    default: postgres://forum:postgres@localhost:5432/forum_test
outputs:
  database_url:
    value: ${{ inputs.database_url }}
runs:
  using: composite
  steps:
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        # bundler-cache automatically installs gems
        bundler-cache: true
        cache-version: 1

    - name: Set up node
      uses: actions/setup-node@v2
      with:
        node-version: '16.13.1'
        cache: 'yarn'
    - name: Install yarn dependencies
      shell: bash
      run: yarn install --frozen-lockfile

    - name: Set up database
      env:
        RAILS_ENV: ${{ inputs.rails_env }}
        DATABASE_URL: ${{ inputs.database_url }}
      shell: bash
      run: bundle exec rake db:schema:load
